name: simple_document_scanner
description: Scan document into PDF
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  provider: ^6.0.5
  reorderable_grid_view: ^2.2.6
  photo_view: ^0.14.0
  pdf: ^3.10.1
  lecle_downloads_path_provider: ^0.0.2+8
  intl: ^0.18.1
  url_launcher: ^6.1.11
  open_file_plus: ^3.4.1
  device_info_plus: ^9.0.2

  collection: any
  cunning_document_scanner: ^1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
